import { dance, bk1, bk2, bk3, bk4, bk5, bk8, tb, bk10, bk14, bk15, bk22, } from "../assets";

const data = [ 
    {
        title:'Lagos Wahala',
        description :'A Novel',
        PosterURL: bk4,
        author: 'Pheecamila',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'The crush',
        description :'A Novel',
        PosterURL:  bk22,
        author: 'Pheechue',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Marriage Mart',
        description :'A Novel',
        PosterURL:  bk5,
        author: 'Zuni',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Tradition',
        description :'A Novel',
        PosterURL: bk15,
        author: 'Pheetemee',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: bk3,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: bk2,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: dance,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: tb,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: bk14,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: bk10,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: bk8,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: bk1,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: dance,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: dance,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: dance,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    
]

export default data;