import { dance, bk1, bk2, bk3, bk4, bk5, bk8, tb, bk10, bk14, bk15, bk22, haus, ladies, Kevin, } from "../assets";

const data = [ 
    {
        title:'Lagos Wahala',
        description :'A Novel',
        coverImage: bk4,
        author: 'Pheecamila',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'The crush',
        description :'A Novel',
        coverImage:  bk22,
        author: 'Pheechue',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Marriage Mart',
        description :'A Novel',
        coverImage:  bk5,
        author: 'Zuni',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Tradition',
        description :'A Novel',
        coverImage: bk15,
        author: 'Pheetemee',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        coverImage: bk3,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        coverImage: Kevin,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        coverImage: bk8,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        coverImage: tb,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        coverImage: bk14,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        coverImage: bk10,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        coverImage: dance,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        coverImage: bk1,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        coverImage: bk2,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        coverImage: ladies,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        coverImage: haus,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    
]

export default data;