import dance from "../assets/res/dance.jpg"

const data = [ 
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: dance,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: dance,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: dance,
        author: 'David',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: dance,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: dance,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: dance,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: dance,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: dance,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: dance,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: dance,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: dance,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: dance,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: dance,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: dance,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    {
        title:'Bookcard',
        description :'A Novel',
        PosterURL: dance,
        author: 'Author',
        publisher: 'Publisher',
        year:'Year',
        genre: 'Genre',
    },
    
]

export default data;